/**
 * SkillGap AI — Analysis orchestrator.
 *
 * resume text ─┬─► skill extraction ─┐
 *              ├─► profile signals ──┼─► matching engine ─► score + gaps
 * job desc ────┴─► JD parsing ───────┘        │
 *                                             ├─► roadmap generator
 *                                             ├─► project recommender
 *                                             └─► career recommender (ML + skills)
 */

import { and, eq, sql } from "drizzle-orm";
import { db } from "@/db";
import { analyses, analysisSkills, skills as skillsTable, users } from "@/db/schema";
import { findRole, JOB_ROLES, type JobRole } from "@/data/jobRoles";
import { SKILLS, type SkillCategory } from "@/data/skills";
import { predictJobCategory } from "@/ml/classifier";
import { getModel } from "@/ml/modelStore";
import { parseJobDescription, type ParsedJobDescription } from "./jdParser";
import { computeMatch, DEFAULT_WEIGHTS, type MatchResult, type SkillGapItem } from "./matcher";
import { recommendCareers, recommendProjects, type CareerMatch, type ScoredProject } from "./recommender";
import { analyzeResumeQuality, type ResumeQuality } from "./resumeQuality";
import { buildRoadmap, type LearningRoadmap } from "./roadmap";
import { extractProfile, type ResumeProfile } from "./resumeParser";
import { computeSimilarity, type SimilarityResult } from "./similarity";
import { extractSkills, skillsByCategory, type ExtractedSkill } from "./skillExtractor";

export interface AnalyzeInput {
  resumeText: string;
  fileName?: string | null;
  fileSize?: number | null;
  parseMethod?: string;
  warnings?: string[];
  targetRoleId?: string | null;
  jobDescription?: string | null;
  candidateName?: string | null;
  candidateEmail?: string | null;
  source?: "upload" | "paste" | "demo";
  weights?: Partial<typeof DEFAULT_WEIGHTS>;
  hoursPerWeek?: number;
  persist?: boolean;
}

export interface AnalysisResult {
  id: string | null;
  createdAt: string;
  candidate: {
    name: string | null;
    email: string | null;
    experienceYears: number;
    education: string[];
    certifications: string[];
    projectTitles: string[];
    links: string[];
  };
  resume: {
    fileName: string | null;
    fileSize: number | null;
    method: string;
    chars: number;
    words: number;
    warnings: string[];
  };
  targetRole: {
    id: string;
    name: string;
    family: string;
    summary: string;
    minExperienceYears: number;
    responsibilities: string[];
  } | null;
  jd: {
    source: ParsedJobDescription["source"];
    requiredSkills: ParsedJobDescription["requiredSkills"];
    preferredSkills: ParsedJobDescription["preferredSkills"];
    detectedRoleConfidence: number;
  };
  skills: ExtractedSkill[];
  skillCategories: Array<{ category: SkillCategory; total: number; items: ExtractedSkill[] }>;
  match: MatchResult;
  similarity: SimilarityResult;
  roadmap: LearningRoadmap;
  quality: ResumeQuality;
  projects: ScoredProject[];
  careers: CareerMatch[];
  ml: {
    algorithm: string;
    topPrediction: string | null;
    predictions: Array<{ label: string; probability: number }>;
  };
  prioritySkills: SkillGapItem[];
  stats: {
    matchedCount: number;
    missingCount: number;
    partialCount: number;
    highPriorityCount: number;
    projectCount: number;
    totalRequired: number;
    totalHours: number;
  };
  disclaimer: string;
}

const DISCLAIMER =
  "Estimated compatibility score generated by SkillGap AI from the resume text and job requirements. It is a learning aid, not a hiring decision or guarantee.";

export async function analyzeResume(input: AnalyzeInput): Promise<AnalysisResult> {
  const resumeText = (input.resumeText ?? "").trim();
  if (resumeText.length < 50) {
    throw new Error("The resume text is too short to analyze (minimum 50 characters).");
  }

  const role = findRole(input.targetRoleId) ?? null;
  const skills = extractSkills(resumeText);
  const profile: ResumeProfile = extractProfile(resumeText);

  const jd = parseJobDescription(input.jobDescription, role?.id ?? input.targetRoleId);
  const effectiveRole: JobRole | null = role ?? jd.detectedRole;

  const jdTextForSimilarity =
    (input.jobDescription && input.jobDescription.trim().length > 40
      ? input.jobDescription
      : buildJdTextFromRole(effectiveRole)) || "";

  const similarity = computeSimilarity(resumeText, jdTextForSimilarity);
  const match = computeMatch({
    resumeSkills: skills,
    required: jd.requiredSkills,
    preferred: jd.preferredSkills,
    profile,
    role: effectiveRole,
    similarity: similarity.score,
    weights: input.weights,
  });

  const gaps: SkillGapItem[] = [...match.missing, ...match.partial.filter((p) => p.type === "required"), ...match.preferredMissing];
  const roadmap = buildRoadmap(gaps, { hoursPerWeek: input.hoursPerWeek ?? 10, roleId: effectiveRole?.id ?? null });
  const quality = analyzeResumeQuality(resumeText, skills, profile);

  const artifact = await getModel();
  const predictions = predictJobCategory(artifact, resumeText, 6);
  const careerTargets = predictions.map((p) => ({ label: p.label, probability: p.probability }));
  void careerTargets;

  const projects = recommendProjects(
    [...match.missing.map((m) => m.name), ...match.preferredMissing.map((m) => m.name)],
    effectiveRole,
    profile.experienceYears,
  );
  const careers = recommendCareers(skills, resumeText, predictions, null, 6);

  const prioritySkills = [...match.missing, ...match.preferredMissing]
    .slice()
    .sort((a, b) => b.priorityScore - a.priorityScore);

  const result: AnalysisResult = {
    id: null,
    createdAt: new Date().toISOString(),
    candidate: {
      name: input.candidateName ?? profile.name,
      email: input.candidateEmail ?? profile.email,
      experienceYears: profile.experienceYears,
      education: profile.education,
      certifications: profile.certifications,
      projectTitles: profile.projectTitles,
      links: profile.links,
    },
    resume: {
      fileName: input.fileName ?? null,
      fileSize: input.fileSize ?? null,
      method: input.parseMethod ?? "text",
      chars: resumeText.length,
      words: resumeText.split(/\s+/).filter(Boolean).length,
      warnings: input.warnings ?? [],
    },
    targetRole: effectiveRole
      ? {
          id: effectiveRole.id,
          name: effectiveRole.name,
          family: effectiveRole.family,
          summary: effectiveRole.summary,
          minExperienceYears: effectiveRole.minExperienceYears,
          responsibilities: effectiveRole.responsibilities,
        }
      : null,
    jd: {
      source: jd.source,
      requiredSkills: jd.requiredSkills,
      preferredSkills: jd.preferredSkills,
      detectedRoleConfidence: Number(jd.detectedRoleConfidence.toFixed(2)),
    },
    skills,
    skillCategories: skillsByCategory(skills),
    match,
    similarity,
    roadmap,
    quality,
    projects,
    careers,
    ml: {
      algorithm: artifact.algorithm,
      topPrediction: predictions[0]?.label ?? null,
      predictions,
    },
    prioritySkills,
    stats: {
      matchedCount: match.matched.length,
      missingCount: match.missing.length,
      partialCount: match.partial.length,
      highPriorityCount: prioritySkills.filter((p) => p.priority === "HIGH").length,
      projectCount: projects.length,
      totalRequired: match.coverage.requiredTotal,
      totalHours: roadmap.totalHours,
    },
    disclaimer: DISCLAIMER,
  };

  if (input.persist !== false) {
    try {
      result.id = await persistAnalysis(result, input.candidateEmail ?? profile.email);
    } catch (error) {
      console.warn("[skillgap-ai] persistence skipped:", (error as Error).message);
    }
  }

  return result;
}

function buildJdTextFromRole(role: JobRole | null): string {
  if (!role) return "";
  return [
    role.name,
    role.summary,
    ...role.responsibilities,
    "Required skills: " + role.required.map((r) => r.skill).join(", "),
    "Preferred skills: " + role.preferred.map((r) => r.skill).join(", "),
  ].join(" ");
}

/* --------------------------------------------------------------- persistence */

async function ensureSkillRows(): Promise<void> {
  try {
    const [{ count }] = await db.select({ count: sql<number>`count(*)::int` }).from(skillsTable);
    if ((count ?? 0) >= SKILLS.length) return;
    await db
      .insert(skillsTable)
      .values(SKILLS.map((s) => ({ name: s.name, category: s.category, demand: s.demand, hours: s.hours })))
      .onConflictDoNothing();
  } catch (error) {
    console.warn("[skillgap-ai] skill seed skipped:", (error as Error).message);
  }
}

async function resolveUser(name: string | null, email: string | null): Promise<number | null> {
  if (!email) return null;
  try {
    const existing = await db.select().from(users).where(eq(users.email, email)).limit(1);
    if (existing[0]) return existing[0].id;
    const [created] = await db
      .insert(users)
      .values({ name: name ?? email.split("@")[0], email })
      .returning({ id: users.id });
    return created?.id ?? null;
  } catch {
    return null;
  }
}

export async function persistAnalysis(result: AnalysisResult, email: string | null): Promise<string> {
  await ensureSkillRows();
  const userId = await resolveUser(result.candidate.name, email);

  const [row] = await db
    .insert(analyses)
    .values({
      userId,
      candidateName: result.candidate.name,
      candidateEmail: result.candidate.email,
      targetRoleId: result.targetRole?.id ?? null,
      targetRoleName: result.targetRole?.name ?? null,
      matchScore: result.match.matchScore,
      projectedScore: result.match.projectedScore,
      resumeChars: result.resume.chars,
      skillsFound: result.skills.length,
      missingCount: result.stats.missingCount,
      source: "analysis",
      jdProvided: result.jd.source !== "dataset",
      mlPrediction: result.ml.topPrediction,
      payload: result as unknown as Record<string, unknown>,
    })
    .returning({ id: analyses.id });

  const skillRows = await db.select({ id: skillsTable.id, name: skillsTable.name }).from(skillsTable);
  const skillIdByName = new Map(skillRows.map((s) => [s.name.toLowerCase(), s.id]));

  const rows = [...result.match.matched, ...result.match.partial, ...result.match.missing, ...result.match.preferredMissing];
  if (rows.length) {
    await db.insert(analysisSkills).values(
      rows.map((item) => ({
        analysisId: row.id,
        skillId: skillIdByName.get(item.name.toLowerCase()) ?? null,
        skillName: item.name,
        category: item.category,
        status: item.status,
        priority: item.priority,
        type: item.type,
        importance: item.importance,
      })),
    );
  }

  return row.id;
}

export async function loadAnalysis(id: string): Promise<AnalysisResult | null> {
  const rows = await db.select().from(analyses).where(eq(analyses.id, id)).limit(1);
  if (!rows[0]) return null;
  const result = rows[0].payload as unknown as AnalysisResult;
  return { ...result, id: rows[0].id, createdAt: rows[0].createdAt.toISOString() };
}

export async function recentAnalyses(limit = 8) {
  const rows = await db
    .select({
      id: analyses.id,
      candidateName: analyses.candidateName,
      targetRoleName: analyses.targetRoleName,
      matchScore: analyses.matchScore,
      projectedScore: analyses.projectedScore,
      createdAt: analyses.createdAt,
      jdProvided: analyses.jdProvided,
    })
    .from(analyses)
    .orderBy(sql`${analyses.createdAt} desc`)
    .limit(limit);
  return rows;
}

export async function saveSkillProgress(analysisId: string, skillName: string, status: string) {
  // upsert-lite: delete then insert keeps the demo dependency-free
  const { skillProgress } = await import("@/db/schema");
  await db.delete(skillProgress).where(and(eq(skillProgress.analysisId, analysisId), eq(skillProgress.skillName, skillName)));
  await db.insert(skillProgress).values({ analysisId, skillName, status });
}

export const SUPPORTED_ROLES = JOB_ROLES;
